<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'WebDriver' => array($vendorDir . '/alexandresalome/php-webdriver/src', $vendorDir . '/alexandresalome/php-webdriver/tests'),
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'Buzz' => array($vendorDir . '/kriswallsmith/buzz/lib'),
);
